name: sasslib CI
on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            pkg
      - name: Archive code
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: .output/test/cc.log
